version: "3.8"

services:
  go-app:
    container_name: my-go-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

    # --- Bagian ini yang ditambahkan ---
    env_file:
      - .env
    # -----------------------------------

    restart: always
